const images = [
  {
    id: "img0001",
    title: "Coastal view at sunrise",
    description:
      "Wide coastal landscape with gentle waves and warm sunrise light.",
    url: "https://picsum.photos/seed/photo1/1200/800",
    thumbnail_url: "https://picsum.photos/seed/photo1/300/200",
    author: "Lorem Picsum",
    license: "Free to use (check picsum.photos and original source terms)",
    source: "picsum.photos",
  },
  {
    id: "img0002",
    title: "Forest trail",
    description:
      "A shaded forest trail lined with tall trees and dappled sunlight.",
    url: "https://picsum.photos/seed/photo2/1200/800",
    thumbnail_url: "https://picsum.photos/seed/photo2/300/200",
    author: "Lorem Picsum",
    license: "Free to use (check picsum.photos and original source terms)",
    source: "picsum.photos",
  },
  {
    id: "img0003",
    title: "City skyline at dusk",
    description:
      "Urban skyline with lights beginning to glow as dusk settles in.",
    url: "https://picsum.photos/seed/photo3/1200/800",
    thumbnail_url: "https://picsum.photos/seed/photo3/300/200",
    author: "Lorem Picsum",
    license: "Free to use (check picsum.photos and original source terms)",
    source: "picsum.photos",
  },
  {
    id: "img0004",
    title: "Mountain lake",
    description: "Clear mountain lake reflecting surrounding peaks and sky.",
    url: "https://picsum.photos/seed/photo4/1200/800",
    thumbnail_url: "https://picsum.photos/seed/photo4/300/200",
    author: "Lorem Picsum",
    license: "Free to use (check picsum.photos and original source terms)",
    source: "picsum.photos",
  },
  {
    id: "img0005",
    title: "Rustic wooden door",
    description:
      "Close-up of a textured rustic wooden door with metal hardware.",
    url: "https://picsum.photos/seed/photo5/1200/800",
    thumbnail_url: "https://picsum.photos/seed/photo5/300/200",
    author: "Lorem Picsum",
    license: "Free to use (check picsum.photos and original source terms)",
    source: "picsum.photos",
  },
  {
    id: "img0006",
    title: "Desert dunes",
    description: "Sweeping sand dunes under a clear sky with rippled textures.",
    url: "https://picsum.photos/seed/photo6/1200/800",
    thumbnail_url: "https://picsum.photos/seed/photo6/300/200",
    author: "Lorem Picsum",
    license: "Free to use (check picsum.photos and original source terms)",
    source: "picsum.photos",
  },
  {
    id: "img0007",
    title: "Close-up flower",
    description:
      "Macro shot of a single flower showing delicate petals and texture.",
    url: "https://picsum.photos/seed/photo7/1200/800",
    thumbnail_url: "https://picsum.photos/seed/photo7/300/200",
    author: "Lorem Picsum",
    license: "Free to use (check picsum.photos and original source terms)",
    source: "picsum.photos",
  },
  {
    id: "img0008",
    title: "Street market",
    description: "Bustling street market scene with stalls and shoppers.",
    url: "https://picsum.photos/seed/photo8/1200/800",
    thumbnail_url: "https://picsum.photos/seed/photo8/300/200",
    author: "Lorem Picsum",
    license: "Free to use (check picsum.photos and original source terms)",
    source: "picsum.photos",
  },
  {
    id: "img0009",
    title: "Snowy path",
    description: "Snow-covered path winding through a quiet winter landscape.",
    url: "https://picsum.photos/seed/photo9/1200/800",
    thumbnail_url: "https://picsum.photos/seed/photo9/300/200",
    author: "Lorem Picsum",
    license: "Free to use (check picsum.photos and original source terms)",
    source: "picsum.photos",
  },
  {
    id: "img0010",
    title: "Vintage bicycle",
    description:
      "A vintage bicycle leaning against a brick wall in soft light.",
    url: "https://picsum.photos/seed/photo10/1200/800",
    thumbnail_url: "https://picsum.photos/seed/photo10/300/200",
    author: "Lorem Picsum",
    license: "Free to use (check picsum.photos and original source terms)",
    source: "picsum.photos",
  },
  {
    id: "img0011",
    title: "Ocean cliff",
    description:
      "Rocky ocean cliff with waves crashing below under a cloudy sky.",
    url: "https://picsum.photos/seed/photo11/1200/800",
    thumbnail_url: "https://picsum.photos/seed/photo11/300/200",
    author: "Lorem Picsum",
    license: "Free to use (check picsum.photos and original source terms)",
    source: "picsum.photos",
  },
  {
    id: "img0012",
    title: "Autumn leaves",
    description: "Close-up of colorful autumn leaves on the ground.",
    url: "https://picsum.photos/seed/photo12/1200/800",
    thumbnail_url: "https://picsum.photos/seed/photo12/300/200",
    author: "Lorem Picsum",
    license: "Free to use (check picsum.photos and original source terms)",
    source: "picsum.photos",
  },
  {
    id: "img0013",
    title: "Night stars",
    description:
      "Clear night sky filled with stars over a silhouette of trees.",
    url: "https://picsum.photos/seed/photo13/1200/800",
    thumbnail_url: "https://picsum.photos/seed/photo13/300/200",
    author: "Lorem Picsum",
    license: "Free to use (check picsum.photos and original source terms)",
    source: "picsum.photos",
  },
  {
    id: "img0014",
    title: "Coffee cup",
    description: "Top-down view of a steaming cup of coffee on a wooden table.",
    url: "https://picsum.photos/seed/photo14/1200/800",
    thumbnail_url: "https://picsum.photos/seed/photo14/300/200",
    author: "Lorem Picsum",
    license: "Free to use (check picsum.photos and original source terms)",
    source: "picsum.photos",
  },
  {
    id: "img0015",
    title: "Countryside road",
    description: "A quiet countryside road bordered by fields and hedgerows.",
    url: "https://picsum.photos/seed/photo15/1200/800",
    thumbnail_url: "https://picsum.photos/seed/photo15/300/200",
    author: "Lorem Picsum",
    license: "Free to use (check picsum.photos and original source terms)",
    source: "picsum.photos",
  },
  {
    id: "img0016",
    title: "Portrait person",
    description: "Portrait of a person looking thoughtfully toward the camera.",
    url: "https://picsum.photos/seed/photo16/1200/800",
    thumbnail_url: "https://picsum.photos/seed/photo16/300/200",
    author: "Lorem Picsum",
    license: "Free to use (check picsum.photos and original source terms)",
    source: "picsum.photos",
  },
  {
    id: "img0017",
    title: "Boat on lake",
    description: "Small wooden boat floating on a calm lake at dawn.",
    url: "https://picsum.photos/seed/photo17/1200/800",
    thumbnail_url: "https://picsum.photos/seed/photo17/300/200",
    author: "Lorem Picsum",
    license: "Free to use (check picsum.photos and original source terms)",
    source: "picsum.photos",
  },
  {
    id: "img0018",
    title: "Market produce",
    description:
      "Fresh fruits and vegetables displayed at an outdoor market stall.",
    url: "https://picsum.photos/seed/photo18/1200/800",
    thumbnail_url: "https://picsum.photos/seed/photo18/300/200",
    author: "Lorem Picsum",
    license: "Free to use (check picsum.photos and original source terms)",
    source: "picsum.photos",
  },
  {
    id: "img0019",
    title: "Historic building",
    description:
      "Facade of an old historic building with architectural details.",
    url: "https://picsum.photos/seed/photo19/1200/800",
    thumbnail_url: "https://picsum.photos/seed/photo19/300/200",
    author: "Lorem Picsum",
    license: "Free to use (check picsum.photos and original source terms)",
    source: "picsum.photos",
  },
  {
    id: "img0020",
    title: "Playful puppy",
    description: "A playful puppy running on grass with ears flapping.",
    url: "https://picsum.photos/seed/photo20/1200/800",
    thumbnail_url: "https://picsum.photos/seed/photo20/300/200",
    author: "Lorem Picsum",
    license: "Free to use (check picsum.photos and original source terms)",
    source: "picsum.photos",
  },
  {
    id: "img0021",
    title: "Modern interior",
    description: "Minimal modern interior with clean lines and natural light.",
    url: "https://picsum.photos/seed/photo21/1200/800",
    thumbnail_url: "https://picsum.photos/seed/photo21/300/200",
    author: "Lorem Picsum",
    license: "Free to use (check picsum.photos and original source terms)",
    source: "picsum.photos",
  },
  {
    id: "img0022",
    title: "Bridge over river",
    description: "An elegant bridge arching over a slow-moving river.",
    url: "https://picsum.photos/seed/photo22/1200/800",
    thumbnail_url: "https://picsum.photos/seed/photo22/300/200",
    author: "Lorem Picsum",
    license: "Free to use (check picsum.photos and original source terms)",
    source: "picsum.photos",
  },
  {
    id: "img0023",
    title: "Morning fog",
    description: "Low fog drifting through a meadow at sunrise.",
    url: "https://picsum.photos/seed/photo23/1200/800",
    thumbnail_url: "https://picsum.photos/seed/photo23/300/200",
    author: "Lorem Picsum",
    license: "Free to use (check picsum.photos and original source terms)",
    source: "picsum.photos",
  },
  {
    id: "img0024",
    title: "Colorful mural",
    description: "A vivid street mural covering the side of a building.",
    url: "https://picsum.photos/seed/photo24/1200/800",
    thumbnail_url: "https://picsum.photos/seed/photo24/300/200",
    author: "Lorem Picsum",
    license: "Free to use (check picsum.photos and original source terms)",
    source: "picsum.photos",
  },
  {
    id: "img0025",
    title: "Rock formation",
    description: "Unique rock formation carved by wind and water over time.",
    url: "https://picsum.photos/seed/photo25/1200/800",
    thumbnail_url: "https://picsum.photos/seed/photo25/300/200",
    author: "Lorem Picsum",
    license: "Free to use (check picsum.photos and original source terms)",
    source: "picsum.photos",
  },
  {
    id: "img0026",
    title: "Children playing",
    description: "Children running and playing outdoors on a sunny day.",
    url: "https://picsum.photos/seed/photo26/1200/800",
    thumbnail_url: "https://picsum.photos/seed/photo26/300/200",
    author: "Lorem Picsum",
    license: "Free to use (check picsum.photos and original source terms)",
    source: "picsum.photos",
  },
  {
    id: "img0027",
    title: "Harvest field",
    description: "Golden harvest field stretching toward a distant horizon.",
    url: "https://picsum.photos/seed/photo27/1200/800",
    thumbnail_url: "https://picsum.photos/seed/photo27/300/200",
    author: "Lorem Picsum",
    license: "Free to use (check picsum.photos and original source terms)",
    source: "picsum.photos",
  },
  {
    id: "img0028",
    title: "Vintage car",
    description: "A restored vintage car parked on a quiet street.",
    url: "https://picsum.photos/seed/photo28/1200/800",
    thumbnail_url: "https://picsum.photos/seed/photo28/300/200",
    author: "Lorem Picsum",
    license: "Free to use (check picsum.photos and original source terms)",
    source: "picsum.photos",
  },
  {
    id: "img0029",
    title: "Winter cabin",
    description: "Cozy cabin surrounded by snow and evergreen trees.",
    url: "https://picsum.photos/seed/photo29/1200/800",
    thumbnail_url: "https://picsum.photos/seed/photo29/300/200",
    author: "Lorem Picsum",
    license: "Free to use (check picsum.photos and original source terms)",
    source: "picsum.photos",
  },
  {
    id: "img0030",
    title: "Flower field",
    description: "Expansive field filled with blooming wildflowers.",
    url: "https://picsum.photos/seed/photo30/1200/800",
    thumbnail_url: "https://picsum.photos/seed/photo30/300/200",
    author: "Lorem Picsum",
    license: "Free to use (check picsum.photos and original source terms)",
    source: "picsum.photos",
  },
  {
    id: "img0031",
    title: "Old bookstore",
    description: "Interior of an old bookstore with shelves of worn books.",
    url: "https://picsum.photos/seed/photo31/1200/800",
    thumbnail_url: "https://picsum.photos/seed/photo31/300/200",
    author: "Lorem Picsum",
    license: "Free to use (check picsum.photos and original source terms)",
    source: "picsum.photos",
  },
  {
    id: "img0032",
    title: "Cobbled street",
    description: "Narrow cobbled street winding through an old town district.",
    url: "https://picsum.photos/seed/photo32/1200/800",
    thumbnail_url: "https://picsum.photos/seed/photo32/300/200",
    author: "Lorem Picsum",
    license: "Free to use (check picsum.photos and original source terms)",
    source: "picsum.photos",
  },
  {
    id: "img0033",
    title: "Busy harbor",
    description: "Boats and cranes in a busy harbor at golden hour.",
    url: "https://picsum.photos/seed/photo33/1200/800",
    thumbnail_url: "https://picsum.photos/seed/photo33/300/200",
    author: "Lorem Picsum",
    license: "Free to use (check picsum.photos and original source terms)",
    source: "picsum.photos",
  },
  {
    id: "img0034",
    title: "Lighthouse",
    description: "A solitary lighthouse standing on a rocky coastline.",
    url: "https://picsum.photos/seed/photo34/1200/800",
    thumbnail_url: "https://picsum.photos/seed/photo34/300/200",
    author: "Lorem Picsum",
    license: "Free to use (check picsum.photos and original source terms)",
    source: "picsum.photos",
  },
  {
    id: "img0035",
    title: "Bokeh lights",
    description:
      "Out-of-focus bokeh lights creating a soft atmospheric background.",
    url: "https://picsum.photos/seed/photo35/1200/800",
    thumbnail_url: "https://picsum.photos/seed/photo35/300/200",
    author: "Lorem Picsum",
    license: "Free to use (check picsum.photos and original source terms)",
    source: "picsum.photos",
  },
  {
    id: "img0036",
    title: "Mountain trail",
    description: "A narrow mountain trail leading up between rocky slopes.",
    url: "https://picsum.photos/seed/photo36/1200/800",
    thumbnail_url: "https://picsum.photos/seed/photo36/300/200",
    author: "Lorem Picsum",
    license: "Free to use (check picsum.photos and original source terms)",
    source: "picsum.photos",
  },
  {
    id: "img0037",
    title: "Sunlit porch",
    description: "A cozy sunlit porch with potted plants and a wooden chair.",
    url: "https://picsum.photos/seed/photo37/1200/800",
    thumbnail_url: "https://picsum.photos/seed/photo37/300/200",
    author: "Lorem Picsum",
    license: "Free to use (check picsum.photos and original source terms)",
    source: "picsum.photos",
  },
  {
    id: "img0038",
    title: "Concert crowd",
    description:
      "Silhouettes of a concert crowd raising hands toward the stage.",
    url: "https://picsum.photos/seed/photo38/1200/800",
    thumbnail_url: "https://picsum.photos/seed/photo38/300/200",
    author: "Lorem Picsum",
    license: "Free to use (check picsum.photos and original source terms)",
    source: "picsum.photos",
  },
  {
    id: "img0039",
    title: "Snowy mountain peak",
    description: "A towering snowy mountain peak against a deep blue sky.",
    url: "https://picsum.photos/seed/photo39/1200/800",
    thumbnail_url: "https://picsum.photos/seed/photo39/300/200",
    author: "Lorem Picsum",
    license: "Free to use (check picsum.photos and original source terms)",
    source: "picsum.photos",
  },
  {
    id: "img0040",
    title: "Rolling hills",
    description:
      "Green rolling hills dotted with wildflowers under a bright sky.",
    url: "https://picsum.photos/seed/photo40/1200/800",
    thumbnail_url: "https://picsum.photos/seed/photo40/300/200",
    author: "Lorem Picsum",
    license: "Free to use (check picsum.photos and original source terms)",
    source: "picsum.photos",
  },
  {
    id: "img0041",
    title: "Urban alley",
    description: "Narrow urban alley with textured walls and scattered light.",
    url: "https://picsum.photos/seed/photo41/1200/800",
    thumbnail_url: "https://picsum.photos/seed/photo41/300/200",
    author: "Lorem Picsum",
    license: "Free to use (check picsum.photos and original source terms)",
    source: "picsum.photos",
  },
  {
    id: "img0042",
    title: "River bend",
    description: "A calm river bending through a lush green valley.",
    url: "https://picsum.photos/seed/photo42/1200/800",
    thumbnail_url: "https://picsum.photos/seed/photo42/300/200",
    author: "Lorem Picsum",
    license: "Free to use (check picsum.photos and original source terms)",
    source: "picsum.photos",
  },
  {
    id: "img0043",
    title: "Colorful sunrise",
    description: "A vibrant sunrise painting the sky with warm hues.",
    url: "https://picsum.photos/seed/photo43/1200/800",
    thumbnail_url: "https://picsum.photos/seed/photo43/300/200",
    author: "Lorem Picsum",
    license: "Free to use (check picsum.photos and original source terms)",
    source: "picsum.photos",
  },
  {
    id: "img0044",
    title: "Coffee shop interior",
    description: "Warm coffee shop interior with customers and soft lighting.",
    url: "https://picsum.photos/seed/photo44/1200/800",
    thumbnail_url: "https://picsum.photos/seed/photo44/300/200",
    author: "Lorem Picsum",
    license: "Free to use (check picsum.photos and original source terms)",
    source: "picsum.photos",
  },
  {
    id: "img0045",
    title: "Sunflower close-up",
    description: "Macro view of a sunflower head showing seeds and petals.",
    url: "https://picsum.photos/seed/photo45/1200/800",
    thumbnail_url: "https://picsum.photos/seed/photo45/300/200",
    author: "Lorem Picsum",
    license: "Free to use (check picsum.photos and original source terms)",
    source: "picsum.photos",
  },
  {
    id: "img0046",
    title: "Foggy bridge",
    description: "A bridge emerging from morning fog across a quiet river.",
    url: "https://picsum.photos/seed/photo46/1200/800",
    thumbnail_url: "https://picsum.photos/seed/photo46/300/200",
    author: "Lorem Picsum",
    license: "Free to use (check picsum.photos and original source terms)",
    source: "picsum.photos",
  },
  {
    id: "img0047",
    title: "Cold coffee",
    description: "Iced coffee in a glass with condensation on a summer day.",
    url: "https://picsum.photos/seed/photo47/1200/800",
    thumbnail_url: "https://picsum.photos/seed/photo47/300/200",
    author: "Lorem Picsum",
    license: "Free to use (check picsum.photos and original source terms)",
    source: "picsum.photos",
  },
  {
    id: "img0048",
    title: "Seaside rocks",
    description:
      "Textured seaside rocks with waves breaking gently around them.",
    url: "https://picsum.photos/seed/photo48/1200/800",
    thumbnail_url: "https://picsum.photos/seed/photo48/300/200",
    author: "Lorem Picsum",
    license: "Free to use (check picsum.photos and original source terms)",
    source: "picsum.photos",
  },
  {
    id: "img0049",
    title: "Old lamp post",
    description: "An antique lamp post glowing softly on a quiet street.",
    url: "https://picsum.photos/seed/photo49/1200/800",
    thumbnail_url: "https://picsum.photos/seed/photo49/300/200",
    author: "Lorem Picsum",
    license: "Free to use (check picsum.photos and original source terms)",
    source: "picsum.photos",
  },
  {
    id: "img0050",
    title: "Children reading",
    description: "Two children reading a storybook together in a cozy nook.",
    url: "https://picsum.photos/seed/photo50/1200/800",
    thumbnail_url: "https://picsum.photos/seed/photo50/300/200",
    author: "Lorem Picsum",
    license: "Free to use (check picsum.photos and original source terms)",
    source: "picsum.photos",
  },
  {
    id: "img0051",
    title: "Rolling fog",
    description: "Morning fog rolling over low hills and trees.",
    url: "https://picsum.photos/seed/photo51/1200/800",
    thumbnail_url: "https://picsum.photos/seed/photo51/300/200",
    author: "Lorem Picsum",
    license: "Free to use (check picsum.photos and original source terms)",
    source: "picsum.photos",
  },
  {
    id: "img0052",
    title: "Market alley",
    description: "Narrow market alley with colorful textiles and goods.",
    url: "https://picsum.photos/seed/photo52/1200/800",
    thumbnail_url: "https://picsum.photos/seed/photo52/300/200",
    author: "Lorem Picsum",
    license: "Free to use (check picsum.photos and original source terms)",
    source: "picsum.photos",
  },
  {
    id: "img0053",
    title: "Quiet chapel",
    description:
      "Sunlight streaming through stained glass into a quiet chapel.",
    url: "https://picsum.photos/seed/photo53/1200/800",
    thumbnail_url: "https://picsum.photos/seed/photo53/300/200",
    author: "Lorem Picsum",
    license: "Free to use (check picsum.photos and original source terms)",
    source: "picsum.photos",
  },
  {
    id: "img0054",
    title: "Fishing boat",
    description: "A small fishing boat moored in shallow, clear water.",
    url: "https://picsum.photos/seed/photo54/1200/800",
    thumbnail_url: "https://picsum.photos/seed/photo54/300/200",
    author: "Lorem Picsum",
    license: "Free to use (check picsum.photos and original source terms)",
    source: "picsum.photos",
  },
];

module.exports = images;
